<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>$(DesktopManagerNet8WindowsTfm);$(DesktopManagerNet10WindowsTfm)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DesktopManager\DesktopManager.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Images\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Spectre.Console" Version="0.50.0" />
    </ItemGroup>

</Project>
